# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RACExercise' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RACExercise
pod 'AFNetworking', '~> 3.1.0'
pod 'MJRefresh', '~> 3.1.12'
pod 'MJExtension', '~> 3.0.13'
pod 'SDAutoLayout', '~> 2.1.3'
pod 'YYText', '~> 1.0.7'
pod 'YYWebImage', '~> 1.0.5'
pod 'ReactiveCocoa','~>2.1.8'

end
